"""Shared content for moon5h1n3.dev. Every design renders from this, so the words,
FAQs and structured data stay identical across designs.

Strings may contain inline HTML (<code>, <a>, <b>). Links to other pages on the
site use {home}, {unbinge} and {last} placeholders, filled in per build.
"""

SITE = {
    "domain": "moon5h1n3.dev",
    "url": "https://moon5h1n3.dev/",
    "author": "MOON5H1N3",
    "github": "https://github.com/MOON5H1N3",
    "title": "moon5h1n3.dev: small self-hosted apps",
    "description": "Small apps by MOON5H1N3, with the code on GitHub: Unbinge releases Plex shows weekly, Last Showing plans your Monzo Vue tickets with Letterboxd, Worth Keeping checks physical media in shops, and Waystamp collects heritage stamps.",
    "intro": "Small apps I built to fix my own problems, now open source for anyone with the same ones.",
    "honesty": "They're vibe coded: written with AI coding tools and tested by hand on my own setup. I'd rather say that up front.",
}

UNBINGE = {
    "slug": "unbinge",
    "name": "Unbinge",
    "repo": "https://github.com/MOON5H1N3/Unbinge",
    "category": "MultimediaApplication",
    "keywords": "Plex, weekly release, binge watching, self-hosted, Docker, Sonarr, appointment TV",
    "title": "Unbinge: release Plex episodes weekly, like real TV",
    "description": "Unbinge is a free, self-hosted Docker app that releases a show from your Plex library a few episodes at a time, on the days you choose, so you watch it weekly instead of binge-watching.",
    "lede": "Your shows, back on a schedule.",
    "summary": "Releases a show from your Plex library a few episodes at a time, on the days you choose, so you watch it weekly instead of bingeing.",
    "intro": "I kept finishing whole series in a weekend and missing the wait between episodes. So I built Unbinge: pick a show from your Plex library, choose the nights it airs, and it drops a few episodes each time. The rest stay out of sight until their slot comes round.",
    "honesty": "I built Unbinge with AI coding tools and run it on my own Plex server. Bug reports and fixes are very welcome.",
    "why": {
        "h": "Make a good show last",
        "p": [
            "When the whole box set is sitting in Plex, \"one more\" turns into six, and a show you were looking forward to is over by Sunday. Willpower doesn't stand much of a chance.",
            "Unbinge takes the choice away, kindly. New episodes turn up in Plex on the nights you picked, like they used to on TV, and there's nothing else there to binge. You get the week of waiting, the guessing, and something to look forward to again.",
        ],
    },
    "how": {
        "h": "How it works",
        "intro": "Unbinge moves episode files between three folders, and tells Plex to rescan after each release.",
        "steps": [
            ("Promote", "Pick a show from your collection and set its release days and episodes per drop. Its files move into the vault."),
            ("Drip", "On each release day, at your chosen time, the next batch moves into the folder your Plex library watches."),
            ("Cooldown", "When the vault runs dry, the show waits one more cycle so you can catch up."),
            ("Graduate", "The whole show, specials included, moves back to your collection and the slot is free for the next one."),
        ],
    },
    "table": {
        "h": "The three folders",
        "cols": ("Folder", "What lives there"),
        "rows": [
            ("Pool (<code>POOL_DIR</code>)", "Your full collection of shows, untouched"),
            ("Vault (<code>VAULT_DIR</code>)", "Episodes of a dripping show that haven't been released yet"),
            ("Released (<code>PLEX_BASE_DIR</code>)", "Episodes that have been released, watched by a Plex library"),
        ],
        "after": "",
    },
    "features_h": "What you get",
    "features": [
        "A dashboard of active, cooling-down and paused shows, with pause, resume and release-now",
        "A schedule of upcoming releases, cooldowns and graduations",
        "A calendar feed at <code>/calendar.ics</code>, so releases show up in your calendar app",
        "A queue to start the next show automatically when one finishes, or on a date",
        "A preview of the next drop, plus excluding episodes and matching oddly named files by hand",
        "History, with one-click undo of the last release",
        "Dry-run mode, to see what would happen without moving any files",
        "Webhook notifications and a self-updating Discord schedule message",
        "Optional TVDB posters, genres and recommendations from your collection",
        "Optional Sonarr connection to show real air dates",
        "Automatic database backups and missed-run detection",
        "Optional password login, and a <code>/health</code> endpoint for Docker",
    ],
    "install": {
        "h": "Install with Docker",
        "intro": "You need Docker with Compose, a Plex server, and a Plex token. Keep your three folders on the same drive so moves are instant.",
        "steps": [
            {"h": "Get the code", "code": "git clone https://github.com/MOON5H1N3/Unbinge.git\ncd Unbinge"},
            {"h": "Add your Plex details",
             "p": ["Create a file called <code>.env</code> next to <code>docker-compose.yaml</code>:"],
             "code": "PLEX_URL=http://192.168.1.10:32400\nPLEX_TOKEN=your-plex-token\nPLEX_LIBRARY_ID=5",
             "after": ["Plex explains <a href=\"https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/\">how to find your token</a>. The library ID is the number after <code>source=</code> in the address bar when you open that library in Plex Web."]},
            {"h": "Point it at your media",
             "p": ["Edit the volumes and folder paths in <code>docker-compose.yaml</code>. The <code>*_DIR</code> values are paths inside the container, so they must sit under a mounted volume:"],
             "code": "services:\n  unbinge:\n    build: .\n    container_name: unbinge\n    restart: unless-stopped\n    ports:\n      - \"5000:5000\"\n    env_file: .env\n    environment:\n      TZ: Europe/London\n      POOL_DIR: /media/tv\n      VAULT_DIR: /media/unbinge/vault\n      PLEX_BASE_DIR: /media/unbinge/released\n      DB_PATH: /config/drip_schedule.db\n    volumes:\n      - ./config:/config\n      - /path/to/your/media:/media",
             "after": ["Set <code>TZ</code> to your timezone. Without it the container runs on UTC and releases fire at the wrong hour for half the year."]},
            {"h": "Start it", "code": "docker compose up -d --build",
             "after": ["Open <code>http://localhost:5000</code>, then add a Plex library that points at the released folder. Released episodes will appear there."]},
            {"h": "Update it later", "code": "./update.sh",
             "after": ["The script backs up your database, pulls the latest code, rebuilds the container and waits until it's healthy again."]},
        ],
    },
    "options": {
        "h": "Optional settings",
        "rows": [
            ("<code>UNBINGE_PASSWORD</code>", "Turns on the login page. Leave it unset for no login."),
            ("<code>WEBHOOK_URL</code>", "Sends a message on each release, failure or missed run"),
            ("<code>DISCORD_SCHEDULE_WEBHOOK_URL</code>", "Keeps a live schedule message up to date in Discord"),
            ("<code>TVDB_API_KEY</code>, <code>TVDB_PIN</code>", "Posters, genres and recommendations"),
            ("<code>SONARR_URL</code>, <code>SONARR_API_KEY</code>", "Shows real upcoming air dates"),
        ],
        "after": "The daily release time defaults to 03:00. You can change it, and the integrations, on the Settings page.",
    },
    "faq": [
        ("How do I release Plex episodes weekly instead of all at once?",
         "Install Unbinge, pick a show, and choose its release days and how many episodes drop each time. Unbinge keeps the unreleased episodes in a separate folder and moves the next batch into your Plex library on each release day, then tells Plex to rescan."),
        ("Does Unbinge delete or copy my files?",
         "Neither. It moves files between your collection, the vault and the released folder, and moves the whole show back to your collection when it finishes. You can undo the last release from the History page, and dry-run mode shows what would happen without moving anything."),
        ("Does it work with Jellyfin or Emby?",
         "It's built for Plex. The folder moves would work with any media server that watches a folder, but only Plex is told to rescan after a release."),
        ("Do I need Sonarr?",
         "No. Sonarr is optional and only adds real upcoming air dates. Unbinge works on shows you already have."),
        ("What happens to specials?",
         "Specials are never released on the schedule. They move back to your collection with the rest of the show when it graduates."),
        ("What if my server was off at release time?",
         "Unbinge notices when the last check was more than a day ago and warns you that releases may have been missed. You can release a show straight away from the dashboard."),
        ("Can I see what's coming up?",
         "Yes. The Schedule page lists upcoming releases, cooldowns and graduations, and you can subscribe to the same schedule in your calendar app."),
        ("I used Driparr. Is this the same app?",
         "Yes. Unbinge used to be called Driparr. Your database, settings and folders carry over, and the old <code>DRIPARR_PASSWORD</code> setting still works."),
        ("Is Unbinge free?",
         "Yes. It's open source under the MIT licence. You run it on your own hardware, and nothing is sent anywhere except to the services you connect."),
        ("Was Unbinge written with AI?",
         "Yes, it's vibe coded: written with AI coding tools, then tested by hand on a real Plex setup. The source is open, so you can read exactly what it does before you run it."),
    ],
    "footer": [
        "Unbinge is MIT licensed and made by <a href=\"https://github.com/MOON5H1N3\">MOON5H1N3</a>. It isn't affiliated with Plex.",
    ],
    "sibling": ("last", "Last Showing", "plans your Monzo Vue tickets around your Letterboxd taste"),
}

LAST = {
    "slug": "last-showing",
    "name": "Last Showing",
    "repo": "https://github.com/MOON5H1N3/last-showing",
    "category": "EntertainmentApplication",
    "keywords": "Monzo Perks, Vue cinema, Letterboxd, film recommendations, self-hosted, Docker, Discord bot",
    "title": "Last Showing: plan your Monzo Vue tickets with Letterboxd",
    "description": "Last Showing is a free, self-hosted Docker app that picks which films to use your monthly Monzo Vue tickets on, based on your Letterboxd ratings and how long each film is likely to stay showing.",
    "lede": "Use your Monzo Vue tickets on the films you'll love, before they leave.",
    "summary": "Plans which films to use your Monzo Vue tickets on, from your Letterboxd taste and how long each film is likely to stay showing.",
    "intro": "A free, self-hosted Docker app that reads your Vue's listings, learns your taste from Letterboxd, and predicts how long each film will stay on. Each month it tells you which films to spend your tickets on and when to go by, in a Discord DM and on a dashboard.",
    "honesty": "I built Last Showing with AI coding tools and use it for my own tickets. Not affiliated with Vue Entertainment, Monzo or Letterboxd.",
    "why": {
        "h": "One ticket a month. Which film?",
        "p": [
            "Monzo Perks gives you a Vue ticket every month, and other schemes give you more. The hard part is choosing. The film you'd love most might be on for weeks, while a smaller one you'd also love disappears on Thursday.",
            "Last Showing weighs both. It spends your tickets on the films you'll rate highly that are about to leave, and saves the ones that will still be around, or that are just as good on a TV, for later.",
        ],
    },
    "how": {
        "h": "How it decides",
        "intro": "Four questions, asked again every morning.",
        "steps": [
            ("What's on", "It reads your Vue's listings, including the coming-soon list, which runs months ahead."),
            ("What you'd think of it", "It learns from your Letterboxd ratings which directors, writers, actors, genres and themes you rate above or below your average, and blends that with the community average."),
            ("How long it'll be on", "It compares each film with real past runs at Vue cinemas and counts how many similar films were still showing a week, two weeks and a month later."),
            ("The trade-off", "Films you'd love that are leaving soon go first. Films that suit the big screen get a lift. Quieter ones you'd enjoy as much at home wait."),
        ],
    },
    "table": {
        "h": "What you see",
        "cols": ("Page", "What's there"),
        "rows": [
            ("Plan", "Your ticket picks, films worth paying for, films to catch later at home, and the next two months"),
            ("Films", "Everything showing or coming soon, scored for you, sortable by best for you or leaving soonest"),
            ("Film page", "Trailer, predicted rating with the reasons, the chance it's still on in a week, two weeks and a month, and showtimes"),
            ("Taste", "What it has learned about you, and how close its past guesses were once you rated those films"),
            ("Settings", "Tickets, cinema, how to weigh favourites against urgency, Letterboxd, Discord and backups"),
        ],
        "after": "Mark a film as <b>Want to see</b> and it's fitted into your free tickets across the next three months, soonest-leaving first. Anything that won't fit becomes a paid trip in the month you'd need to go. Used tickets are picked up from your Letterboxd diary, or you can mark them in Discord with <code>/used</code>.",
    },
    "features_h": "What else it does",
    "features": [
        "Hunt: a short \"buy if you see it\" list of the films, books and albums you've loved but don't own, ranked on your rating, how often you've rewatched or played it, and whether it completes a series you've started",
        "Checks you can actually buy a film in the UK before suggesting it, and groups TV episodes you've loved into box sets",
        "Album suggestions from what you play most on Last.fm or Plex",
        "A monthly plan by Discord DM, with buttons to mark films and slash commands like <code>/picks</code> and <code>/refresh</code>",
        "Leaving-soon estimates for every film, from real past runs at Vue cinemas",
        "Early review badges from Rotten Tomatoes, Metacritic and the Guardian, if you add free keys",
        "Buzz on every film page: Letterboxd lists, early watchers and opening-week showings",
        "A record of every prediction, so you can see how close it was once you've rated the film",
        "Break alerts: a DM when a key is rejected or a step keeps failing, and another when it's fixed",
        "Settings for any UK Vue, any number of tickets, and screen types your tickets don't cover",
        "Daily backups, and an optional dashboard password",
    ],
    "install": {
        "h": "Install with Docker",
        "intro": "Setup takes about 15 minutes. You need Docker with Compose, a Letterboxd account, a Discord account and a free TMDB key. It runs on Windows, macOS or Linux.",
        "steps": [
            {"h": "Get the code", "code": "git clone https://github.com/MOON5H1N3/last-showing.git\ncd last-showing"},
            {"h": "Gather your keys",
             "list": [
                 "<b>TMDB:</b> make an account at <a href=\"https://www.themoviedb.org/signup\">themoviedb.org</a>, then request a developer key under Settings, API.",
                 "<b>Discord bot:</b> create an application in the <a href=\"https://discord.com/developers/applications\">Discord developer portal</a>, copy its bot token, and add it to a server you're in so it can DM you. Turn on Developer Mode in Discord to copy your own user ID.",
                 "<b>Letterboxd:</b> export your data from Settings, Data on letterboxd.com and keep the .zip.",
             ],
             "after": ["The <a href=\"https://github.com/MOON5H1N3/last-showing#setup-about-15-minutes\">README</a> walks through each one step by step."]},
            {"h": "Configure and start it",
             "code": "cp .env.example .env\n# fill in TMDB_API_KEY, DISCORD_BOT_TOKEN, DISCORD_USER_ID, LETTERBOXD_USERNAME\ndocker compose up -d --build",
             "after": ["On Windows, use <code>copy</code> instead of <code>cp</code> and edit the file with Notepad. The first build takes a few minutes because it downloads a headless browser to read the listings."]},
            {"h": "Add your Letterboxd export",
             "p": ["Open <code>http://localhost:8095</code>, go to Settings, Letterboxd, and upload the .zip. Pick your Vue and your ticket allowance on the same page. New diary entries arrive automatically after that."]},
        ],
    },
    "options": {
        "h": "Optional: early reviews",
        "rows": [
            ("<code>OMDB_API_KEY</code>", "Rotten Tomatoes and Metacritic scores. Free at <a href=\"https://www.omdbapi.com/apikey.aspx\">omdbapi.com</a>."),
            ("<code>GUARDIAN_API_KEY</code>", "The Guardian's star ratings. Free at <a href=\"https://open-platform.theguardian.com/access/\">open-platform.theguardian.com</a>."),
            ("<code>DASHBOARD_PASSWORD</code>", "Asks for a password before showing the dashboard"),
        ],
        "after": "Reviews appear as a badge on new films and never change the predictions.",
    },
    "faq": [
        ("How do I choose which film to use my Monzo Vue ticket on?",
         "Last Showing does it for you. It predicts how much you'll like each film at your Vue from your Letterboxd ratings, estimates how long each one will stay on, and picks the films you'd rate highly that are about to leave. The plan arrives as a Discord DM at the start of each month."),
        ("Does it work with any Vue cinema?", "Yes, any Vue in the UK. Choose yours on the Settings page."),
        ("Do I need Monzo?",
         "No. Choose Monzo Perks for one ticket a month, a custom number of tickets, or no tickets at all if you just want recommendations and leaving-soon warnings."),
        ("Does it work with Cineworld or Odeon?", "No. It reads Vue's listings only."),
        ("Do I need a Letterboxd account?",
         "Yes. Your ratings are how it learns your taste, and your public diary is how it notices which films you've seen. A larger rating history gives better predictions."),
        ("How does it know when a film is leaving?",
         "It learns from real history: past listings of several London Vues, plus your own cinema's finished runs as they build up. It also notices when Vue stops listing a film before the end of the published week."),
        ("How accurate are the predictions?",
         "It shows you. The Taste page tests its rating guesses on films it hadn't seen, and keeps a record of every prediction so you can see how close it was once you've rated the film yourself."),
        ("Does it book tickets for me?", "No. It plans which films to see and when. You still book through Monzo or Vue as usual."),
        ("Is it free?",
         "Yes. It's open source under the MIT licence and runs on your own computer or server. The TMDB, OMDb and Guardian keys are free too."),
        ("Is Last Showing affiliated with Vue, Monzo or Letterboxd?", "No. It's an independent hobby project."),
        ("Was Last Showing written with AI?",
         "Yes, it's vibe coded: written with AI coding tools, then tested by hand on real tickets. The source is open, so you can read exactly what it does before you run it."),
    ],
    "footer": [
        "Last Showing is MIT licensed and made by <a href=\"https://github.com/MOON5H1N3\">MOON5H1N3</a>. Not affiliated with Vue Entertainment, Monzo or Letterboxd.",
        "Film data from <a href=\"https://www.themoviedb.org/\">TMDB</a>. This product uses the TMDB API but is not endorsed or certified by TMDB. Past listings from <a href=\"https://github.com/clusterflick\">Clusterflick</a>, under CC BY 4.0.",
    ],
    "sibling": ("unbinge", "Unbinge", "releases your Plex shows a few episodes at a time"),
}



WORTH = {
    "slug": "worth-keeping",
    "name": "Worth Keeping",
    "repo": "https://github.com/MOON5H1N3/worth-keeping",
    "category": "LifestyleApplication",
    "keywords": "physical media, barcode scanner, Discogs, Letterboxd, Blu-ray, vinyl, books, collection tracker, self-hosted, Docker, Plex",
    "title": "Worth Keeping: scan a barcode, know if it's worth buying",
    "description": "Worth Keeping is a free, self-hosted Docker app for physical media collectors. Scan a book, DVD, Blu-ray, CD or record in a shop to see if you already own it, whether it fits your taste, and whether the price is a good find in the UK.",
    "lede": "Know if it's worth keeping before you buy it.",
    "summary": "Scan a book, film or record in a shop and see if you already own it, whether it's your taste, and whether the price is a good find.",
    "intro": "A free, self-hosted Docker app for anyone who collects books, DVDs and Blu-rays, CDs and vinyl. Scan a barcode in a charity shop and it tells you whether it's already on your shelf, how it fits your Letterboxd, book app and Plex taste, and whether the price is fair for the UK.",
    "honesty": "I built Worth Keeping with AI coding tools and use it on my own collection. Not affiliated with Discogs, Letterboxd, Pagebound, Plex, Last.fm or eBay.",
    "soon": {
        "h": "Coming soon",
        "p": [
            "Worth Keeping isn't released yet. I'm using it on my own collection first, to get the phone app, Hunt and the imports right before anyone else relies on them.",
            "When it's ready, the code will be on GitHub under the MIT licence, with a one-click update file for Windows and a guide to setting up the phone app. It will run in Docker on your own computer, with your shelf kept in one file you can back up.",
        ],
    },
    "why": {
        "h": "Is it a find, or a second copy?",
        "p": [
            "Charity shops and record fairs are full of things you might want, and some you already own. Standing in the aisle, it's hard to remember whether that Blu-ray is on your shelf, whether you liked the film, or whether £4 is a bargain.",
            "Worth Keeping answers all three from one scan, using your own shelf and your own ratings. It works with no signal too, because your phone keeps a copy of your shelf.",
        ],
    },
    "how": {
        "h": "How a scan works",
        "intro": "Point your phone at the barcode, add the shop price if you like, and you get one plain verdict.",
        "steps": [
            ("Scan", "Use your phone's camera, or type the barcode. Batch mode scans a whole shelf in one go."),
            ("Look it up", "Books come from Open Library, CDs and records from Discogs, and films and everything else from UPCitemdb."),
            ("Check your taste", "Your Letterboxd rating or watchlist, your book app rating or to-read list, and whether it's already on your Plex."),
            ("Get a verdict", "Good find, Fair price, Too much, Upgrade, or On your shelf. Tap Bought it and it's added, with what you paid and where."),
        ],
    },
    "table": {
        "h": "The verdicts",
        "cols": ("Verdict", "What it means"),
        "rows": [
            ("Good find", "Cheaper than it usually sells for. Music is priced against Discogs; books and films against eBay UK listings."),
            ("Fair price", "About what it usually goes for"),
            ("Too much", "You'd usually pay less elsewhere"),
            ("Upgrade", "You own another edition or a lesser format, such as the DVD of a Blu-ray in your hand"),
            ("On your shelf", "You already have this one"),
        ],
        "after": "Scans that match your Discogs wantlist say so. The <b>Hunt</b> page lists things you love that you don't own physically yet: anything rated 4★ or more, or on a watchlist or to-read list, plus your Discogs wantlist.",
    },
    "features_h": "What else it does",
    "features": [
        "Hunt: a short \"buy if you see it\" list of the films, books and albums you've loved but don't own, ranked on your rating, how often you've rewatched or played it, and whether it completes a series you've started",
        "Checks you can actually buy a film in the UK before suggesting it, and groups TV episodes you've loved into box sets",
        "Album suggestions from what you play most on Last.fm or Plex",
        "A shelf of everything you own, as covers or a list, searchable and filterable by format",
        "Upgrade spotting, with the option to take the old copy off your shelf",
        "A phone app that keeps your whole shelf on the phone, so scanning works with no signal, and syncs with your computer when you're home",
        "Stats by format and decade, monthly spending, favourite shops, and what Discogs says your collection is worth",
        "A nightly refresh of Discogs and Plex, and covers found for anything missing one",
        "Find duplicates, and download your shelf as a spreadsheet",
        "Imports from Letterboxd, Pagebound, Goodreads or StoryGraph, plus Discogs, Plex, Last.fm and Last Showing connections",
        "One database file, with a backup download in Settings",
    ],
    "install": {
        "h": "Install with Docker",
        "intro": "You need Docker with Compose. Discogs, Letterboxd, a book app and Plex are all optional, and you can connect them later in Settings.",
        "steps": [
            {"h": "Get the code", "code": "git clone https://github.com/MOON5H1N3/worth-keeping.git\ncd worth-keeping"},
            {"h": "Start it", "code": "docker compose up -d --build",
             "after": ["Open <code>http://localhost:8787</code>. Your shelf and settings live in the <code>data</code> folder next to it, and updates never touch it."]},
            {"h": "On Windows, update with one click",
             "p": ["Double-click <code>update.bat</code> in the folder. It pulls the latest version, rebuilds the container and starts it. Run it again whenever there's a new version."]},
            {"h": "Use it on your phone",
             "p": ["Android only installs a web app that works offline from an https address. Worth Keeping can get one that only works on your home network, so nothing is opened to the internet. You need a domain on Cloudflare: run <code>setup-https.bat</code> once, then <code>update.bat</code>. The README walks you through it.",
                   "Then, on your home Wi-Fi, open <code>/app/</code> at that address on your phone and choose Install app."]},
        ],
    },
    "options": {
        "h": "Optional connections",
        "rows": [
            ("Discogs", "Your collection, wantlist and music prices"),
            ("Letterboxd", "Upload your export and tick which lists are physical copies you own"),
            ("Book app", "A Pagebound, Goodreads or StoryGraph CSV, with the shelves that mean you own a copy"),
            ("Plex", "Whether you already have a film digitally, and which albums you play most"),
            ("Last.fm", "Your most-played albums, for music suggestions"),
            ("eBay, TMDB and Google Books", "Free developer keys: book and film prices and UK availability, film posters, and book lookups"),
        ],
        "after": "All of these are set up on the Settings page.",
    },
    "faq": [
        ("How do I check if I already own a DVD or record while I'm in a shop?",
         "Scan its barcode with Worth Keeping on your phone. It checks your shelf straight away, even with no signal, and tells you if you own it or own another edition."),
        ("How do I know if a second-hand price is good?",
         "Add the shop price when you scan. Worth Keeping compares it with what the item usually sells for: Discogs for CDs and records, and eBay UK listings for books and films. It then says Good find, Fair price or Too much."),
        ("Does it work with Letterboxd and Discogs?",
         "Yes. Upload your Letterboxd export to see your rating or watchlist on every film you scan, and connect Discogs to import your collection and wantlist."),
        ("Which book apps does it support?",
         "Pagebound, Goodreads and StoryGraph CSV exports. You choose which shelves mean you own a physical copy."),
        ("Does it work without phone signal?",
         "Yes. Your phone keeps a copy of your shelf, so \"do I own it?\" still works. Anything it can't answer is saved and checked when you're back online."),
        ("Why does the phone app need a domain?",
         "Android only installs web apps from https addresses. A domain on Cloudflare lets Worth Keeping get a certificate for an address that only works on your home network, with no tunnel or VPN and nothing open to the internet."),
        ("Where is my data kept?",
         "In one file on your own computer, <code>data/worth-keeping.db</code>. Settings has a backup download."),
        ("Can I get it?", "Not yet. It's coming soon, as free, open-source software (MIT licence) that runs on your own computer."),
        ("Will it be free?", "Yes. It'll be open source under the MIT licence and run on your own computer. The optional eBay, Discogs, TMDB and Last.fm keys are free too."),
        ("Is Worth Keeping affiliated with Discogs, Letterboxd or eBay?", "No. It's an independent hobby project."),
        ("Was Worth Keeping written with AI?",
         "Yes, it's vibe coded: written with AI coding tools, then tested by hand on a real collection. The source is on GitHub, so you can read exactly what it does before you run it."),
    ],
    "footer": [
        "Worth Keeping is made by <a href=\"https://github.com/MOON5H1N3\">MOON5H1N3</a> and will be MIT licensed. Not affiliated with Discogs, Letterboxd, Pagebound, Plex, Last.fm or eBay.",
        "Book data from <a href=\"https://openlibrary.org/\">Open Library</a>. This product uses the TMDB API but is not endorsed or certified by TMDB.",
    ],
    "sibling": ("last", "Last Showing", "plans your Monzo Vue tickets around your Letterboxd taste"),
}

APPS = [UNBINGE, LAST, WORTH]
